name: Sync README to GitHub Pages
on:
  push:
    paths:
      - 'README.md'
      - 'assets/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare docs folder
        run: |
          mkdir -p docs/assets
          cp -r assets/* docs/assets/ 2>/dev/null || true
          cp README.md docs/index.md
          touch docs/.nojekyll

      - name: Commit docs updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.md docs/assets/. docs/.nojekyll
          git commit -m "Sync README to GitHub Pages [auto]" || echo "no changes"
          git push
